language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
  - pip install codecov
  - pip install pytest-cov
# command to run tests
script:
  - cd linefinder
  - pytest --runslow --cov=./
after_success:
  - codecov
